### ISSUE TITLE
Package name convention

### ISSUE THREAD

**Issue by riccardomerolla** [eMDi94/auth-demo#2]
Mi sembra che ci sia una parte dei package che viene dal template che hai utilizzato per creare il progetto iniziale e poi un'altra convenzione.

Utilizza un solo standard, così è più facile capire bene il design dell'applicazione, se vuoi un consiglio utilizza questo pattern:

https://adambien.blog/roller/abien/entry/migration_from_stateless_bce_to

**Comment by eMDi94** [comment]
Ho provato a riorganizzare il codice in modo che le parti core siano in un unico package e la parte web risieda sotto un altro package. Non so se può andare bene così o sono fuori strada.
